name: Enhancement
description: Have any new features you want to see or any ideas to make Straighter better? Here's your place ;)
title: "[ENHANCEMENT] PLEASE REPLACE THIS TEXT WITH A SUMMARY OF YOUR SUGGESTION..."
labels: ["enhancement"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmation Checklist
      options:
        - label: I confirm that this suggestion applies to the **latest release** of Straighter. You can check what the latest version is [on the `Releases` page](https://github.com/idinnovate/Straighter/releases).
          required: true
        - label: I confirm that this suggestion has **NOT** already been made on [the issue tracker](https://github.com/idinnovate/Straighter/issues).
          required: true

  - type: textarea
    id: reason
    attributes:
      label: Please explain your proposal with as many details as necessary (Ex. what you're suggesting, why you're suggesting it, what need you thinks it will fill, who it will benefit, etc...).
    validations:
      required: true
